sudo: false
 
language: java
 
jdk: oraclejdk8
 
cache:
  directories:
  - $HOME/.m2
 
env: DISPLAY=:99.0
  global:
  - GH_REF: github.com/mondo-project/mondo-hawk.git
 
install: true
 
addons:
  apt:
    packages:
    - metacity
 
before_script:
 - sh -e /etc/init.d/xvfb start
 - metacity --sm-disable --replace 2> metacity.err &
 # Specify a display with xvfb for UI testing
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
 - sleep 3 # give xvfb some time to start

script: bash ./deploy.sh 