script: bash ./deploy.sh
sudo: required
language: java
jdk:
- oraclejdk8

addons:
  apt:
    packages:
    - metacity

before_script:
 - sh -e /etc/init.d/xvfb start
 - metacity --sm-disable --replace 2> metacity.err &

env:
  global:
    - GH_REF: github.com/antoniogarmendia/tycho-swtbot-example.git